### ISSUE TITLE
switch to file-relative config

### ISSUE THREAD

**Issue by humanchimp** [humanchimp/stable#25]
I've been thinking of using `.stablerc` files (which would be YAML/JSON files). I have been considering a system where we would pick up the nearest relative .stablerc file. Which would allow different runners to be configured for different sorts of source files. Let's imagine that we keep our unit tests alongside the source files we're covering. Below is an approximation of how our simplified tree might look.
```
.stablerc
src
├── .stablerc
├── Spec.ts
├── Spec.spec.ts
├── Suite.ts
├── Suite.spec.ts
├── describe.ts
├── describe.spec.ts
├── dethunk.ts
└── dethunk.spec.ts
cli
├── .stablerc
├── cli.js
├── commands
│   ├── bundle.js
│   ├── bundle.spec.js
│   ├── run.js
│   └── run.spec.js
└── runners
    ├── eval.js
    ├── eval.spec.js
    ├── isolate.js
    ├── isolate.spec.js
    ├── remote.js
    ├── remote.spec.js
    ├── vm.js
    └── vm.spec.js
```

_Figure 1_: The simplified tree.

The idea here is that, at the top-level `.stablerc`, we could define some project-wide things. Spitballing:

```yaml
---
include: ./**/*.spec.{ts,js}
plugins:
- - timing
  - timeout: 200
- - rescue
- - fixture
  - include: ./spec/fixture/**/*
custom_runners:
- - headless chrome
  - runner: remote
    bin: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
    arguments:
    - --headless
    - --remote-debugging-port=9222
```

_Figure 2_: The base definitions in the `.stablerc` files are inherited by the derived `./src/.stablerc` and `./cli/.stablerc` files found in child directories.

```yaml
---
runners:
- isolate
- headless chrome
```

_Figure 3_: The `./src/.stablerc` file uses the `headless chrome` custom runner defined in the root configuration, selecting it and the hypothetical (planned) `isolate` runner which is a built-in runner which runs each spec in an isolated vm context in Node.js.

```yaml
---
runners:
- isolate
```

_Figure 4_: The `./cli/.stablerc` file selects only the `isolate` runner, since it only makes sense to test the CLI in Node.js (it isn't designed to run in a browser at all, *let alone a *headless* one!*).

The goal here would be that when you run `$ stable` at the root of the project tree, it runs all the specs for the entire project, but only runs the `cli` specs in node, while running the `src` specs in both node and headless chrome, reporting back the merged stream of reports.

If you were to run `$ stable src/**/*.spec.ts` it would run only the specs for the `src` tree, in both `isolate` and `headless chrome`. If you were to run `$ stable cli/**/*.spec.js`, it would run only the specs for the `cli` tree, and only in `isolate`.

I think it's a fantastic idea, although I wish there was a way to golf down some of the complexity
